routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashbordController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');

Route::resource('users', App\Http\Controllers\UserController::class);

Route::resource('teams', App\Http\Controllers\TeamController::class);

Route::resource('teamMembers', App\Http\Controllers\Team_memberController::class);

Route::resource('authors', App\Http\Controllers\AuthorController::class);

Route::resource('categories', App\Http\Controllers\CategoryController::class);

Route::resource('art', App\Http\Controllers\ArtController::class);

Route::get('/', function () { return view('home'); });
Route::get('gallery', function () { return view('gallery'); });
Route::get('contact', function () { return view('contact'); });
Route::get('/index',   [\App\Http\Controllers\HomeController::class, 'index']);
Route::get('lang/{locale}',[\App\Http\Controllers\LanguageController::class,'index']);

Route::get('/gallery',    [FrontController::class,'gallery']);

Route::get('/login',     [AuthController::class,'login'])->name('login');
Route::post('/login',     [AuthController::class,'checklogin']);
Route::get('/logout',    [AuthController::class,'logout'])->name('logout');

Route::get('/dashbord', [\App\Http\Controllers\DashbordController::class, 'dashbord']);

app/Models/Team_member.php
<?php

namespace App\Models;

use Eloquent as Model;



/**
 * Class Team_member
 * @package App\Models
 * @version April 23, 2021, 7:16 pm UTC
 *
 * @property string $team_id
 * @property string $pasition
 * @property string $full_name
 * @property string $info
 */
class Team_member extends Model
{


    public $table = 'team_members';
    



    public $fillable = [
        'team_id',
        'pasition',
        'full_name',
        'info'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'team_id' => 'string',
        'pasition' => 'string',
        'full_name' => 'string',
        'info' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/Team_memberController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\Team_memberDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateTeam_memberRequest;
use App\Http\Requests\UpdateTeam_memberRequest;
use App\Models\Team;
use App\Repositories\Team_memberRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class Team_memberController extends AppBaseController
{
    /** @var  Team_memberRepository */
    private $teamMemberRepository;

    public function __construct(Team_memberRepository $teamMemberRepo)
    {
        $this->teamMemberRepository = $teamMemberRepo;
    }

    /**
     * Display a listing of the Team_member.
     *
     * @param Team_memberDataTable $teamMemberDataTable
     * @return Response
     */
    public function index(Team_memberDataTable $teamMemberDataTable)
    {
        return $teamMemberDataTable->render('team_members.index');
    }

    /**
     * Show the form for creating a new Team_member.
     *
     * @return Response
     */
    public function create()
    {
        $teams = Team::all();

        return view('team_members.create', compact('teams'));
    }

    /**
     * Store a newly created Team_member in storage.
     *
     * @param CreateTeam_memberRequest $request
     *
     * @return Response
     */
    public function store(CreateTeam_memberRequest $request)
    {
        $input = $request->all();

        $teamMember = $this->teamMemberRepository->create($input);

        Flash::success('Team Member saved successfully.');

        return redirect(route('teamMembers.index'));
    }

    /**
     * Display the specified Team_member.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $teamMember = $this->teamMemberRepository->find($id);

        if (empty($teamMember)) {
            Flash::error('Team Member not found');

            return redirect(route('teamMembers.index'));
        }

        return view('team_members.show')->with('teamMember', $teamMember);
    }

    /**
     * Show the form for editing the specified Team_member.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $teamMember = $this->teamMemberRepository->find($id);

        if (empty($teamMember)) {
            Flash::error('Team Member not found');

            return redirect(route('teamMembers.index'));
        }

        return view('team_members.edit')->with('teamMember', $teamMember);
    }

    /**
     * Update the specified Team_member in storage.
     *
     * @param  int              $id
     * @param UpdateTeam_memberRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateTeam_memberRequest $request)
    {
        $teamMember = $this->teamMemberRepository->find($id);

        if (empty($teamMember)) {
            Flash::error('Team Member not found');

            return redirect(route('teamMembers.index'));
        }

        $teamMember = $this->teamMemberRepository->update($request->all(), $id);

        Flash::success('Team Member updated successfully.');

        return redirect(route('teamMembers.index'));
    }

    /**
     * Remove the specified Team_member from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $teamMember = $this->teamMemberRepository->find($id);

        if (empty($teamMember)) {
            Flash::error('Team Member not found');

            return redirect(route('teamMembers.index'));
        }

        $this->teamMemberRepository->delete($id);

        Flash::success('Team Member deleted successfully.');

        return redirect(route('teamMembers.index'));
    }
}

resources/views/team_members/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('teamMembers.index') !!}">Jamoa azosi</a>
      </li>
      <li class="breadcrumb-item active">Yaratish</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Jamoa azosini yaraish</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'teamMembers.store']) !!}

                                   @include('team_members.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/team_members/datatables_actions.blade.php
{!! Form::open(['route' => ['teamMembers.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('teamMembers.show', $id) }}" class='btn btn-ghost-success'>
       <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('teamMembers.edit', $id) }}" class='btn btn-ghost-info'>
       <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-ghost-danger',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/team_members/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('teamMembers.index') !!}">Jamoa azosi</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Jamoa azosini yaratish</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($teamMember, ['route' => ['teamMembers.update', $teamMember->id], 'method' => 'patch']) !!}

                              @include('team_members.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/team_members/fields.blade.php
<!-- Team Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('team_id', 'Team Id:') !!}
    <select class="select" name="team_id" id="team_id">
        @foreach($teams as $team)
            <option value="{{$team->id}}">{{$team->name}}</option>
        @endforeach
    </select>
</div>

<!-- Pasition Field -->
<div class="form-group col-sm-6">
    {!! Form::label('pasition', 'Lavozimi:') !!}
    {!! Form::text('pasition', null, ['class' => 'form-control']) !!}
</div>

<!-- Full Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('full_name', 'Toliq IFO:') !!}
    {!! Form::text('full_name', null, ['class' => 'form-control']) !!}
</div>

<!-- Info Field -->
<div class="form-group col-sm-6">
    {!! Form::label('info', 'Info:') !!}
    {!! Form::text('info', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Saqlash', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('teamMembers.index') }}" class="btn btn-secondary">Bekor qilish</a>
</div>

resources/views/team_members/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Jamoa azolari</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             Jamoa azolari
                             <a class="pull-right" href="{{ route('teamMembers.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('team_members.table')
                              <div class="pull-right mr-3">

                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/team_members/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('teamMembers.index') }}">Jamoa azosi</a>
            </li>
            <li class="breadcrumb-item active">Malumot</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Malumotlar</strong>
                                  <a href="{{ route('teamMembers.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('team_members.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/team_members/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{{ $teamMember->id }}</p>
</div>

<!-- Team Id Field -->
<div class="form-group">
    {!! Form::label('team_id', 'Jamoa Id:') !!}
    <p>{{ $teamMember->team_id }}</p>
</div>

<!-- Pasition Field -->
<div class="form-group">
    {!! Form::label('pasition', 'Lavozimi:') !!}
    <p>{{ $teamMember->pasition }}</p>
</div>

<!-- Full Name Field -->
<div class="form-group">
    {!! Form::label('full_name', 'Toliq FIO:') !!}
    <p>{{ $teamMember->full_name }}</p>
</div>

<!-- Info Field -->
<div class="form-group">
    {!! Form::label('info', 'Info:') !!}
    <p>{{ $teamMember->info }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Yaratilgan vaqti:') !!}
    <p>{{ $teamMember->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Yangilangan vaqti At:') !!}
    <p>{{ $teamMember->updated_at }}</p>
</div>

resources/views/team_members/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush