routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashbordController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');

Route::resource('users', App\Http\Controllers\UserController::class);

Route::resource('teams', App\Http\Controllers\TeamController::class);

Route::resource('teamMembers', App\Http\Controllers\Team_memberController::class);

Route::resource('authors', App\Http\Controllers\AuthorController::class);

Route::resource('categories', App\Http\Controllers\CategoryController::class);

Route::resource('art', App\Http\Controllers\ArtController::class);

Route::get('/', function () { return view('home'); });
Route::get('gallery', function () { return view('gallery'); });
Route::get('contact', function () { return view('contact'); });
Route::get('/index',   [\App\Http\Controllers\HomeController::class, 'index']);
Route::get('lang/{locale}',[\App\Http\Controllers\LanguageController::class,'index']);

Route::get('/gallery',    [FrontController::class,'gallery']);

Route::get('/login',     [AuthController::class,'login'])->name('login');
Route::post('/login',     [AuthController::class,'checklogin']);
Route::get('/logout',    [AuthController::class,'logout'])->name('logout');

Route::get('/dashbord', [\App\Http\Controllers\DashbordController::class, 'dashbord']);

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{config('app.name')}}</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 4.1.1 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@coreui/coreui@2.1.16/dist/css/coreui.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@icon/coreui-icons-free@1.0.1-alpha.1/coreui-icons-free.css">

     <!-- PRO version // if you have PRO version licence than remove comment and use it. -->
    {{--<link rel="stylesheet" href="https://unpkg.com/@coreui/icons@1.0.0/css/brand.min.css">--}}
    {{--<link rel="stylesheet" href="https://unpkg.com/@coreui/icons@1.0.0/css/flag.min.css">--}}
     <!-- PRO version -->

    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/css/flag-icon.min.css">
</head>
<body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">
<header class="app-header navbar">
    <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">
        <img class="navbar-brand-full" src="{{ url('/files/img.png') }}" width="150" height="55"
             alt="InfyOm Logo">
        <img class="navbar-brand-minimized" src="http://infyom.com/images/logo/blue_logo_150x150.jpg" width="30"
             height="30" alt="InfyOm Logo">
    </a>
    <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
        <span class="navbar-toggler-icon"></span>
    </button>

    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item d-md-down-none">
            <a class="nav-link" href="#">
                <i class="icon-bell"></i>
                <span class="badge badge-pill badge-danger">50</span>
            </a>
        </li>
        <li>
            <buttun class="btn bg-secondary" style="margin-left: 5px"><a href="{{ url('/logout') }}" style="color: darkred">Logout</a></buttun>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link" style="margin-right: 10px" data-toggle="dropdown" href="#" role="button"
               aria-haspopup="true" aria-expanded="false">
{{--                {{ Auth::user()->name }}--}}
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-header text-center">
                    <strong>Account</strong>
                </div>
                <a class="dropdown-item" href="#">
                    <i class="fa fa-envelope-o"></i> Messages
                    <span class="badge badge-success">42</span>
                </a>
                <div class="dropdown-header text-center">
                    <strong>Settings</strong>
                </div>
                <a class="dropdown-item" href="#">
                    <i class="fa fa-user"></i> Profile</a>
                <a class="dropdown-item" href="#">
                    <i class="fa fa-wrench"></i> Settings</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">
                    <i class="fa fa-shield"></i> Lock Account</a>
                <a href="{{ url('/logout') }}" class="dropdown-item btn btn-default btn-flat"
                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                    <i class="fa fa-lock"></i>Logout
                </a>
                <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</header>

<div class="app-body">
    @include('layouts.sidebar')
    <main class="main">
        @yield('content')
    </main>
</div>
<footer class="app-footer">
    <div>
        <a href="https://infyom.com">Urgench </a>
        <span>&copy; 2021 Khorezm.</span>
    </div>
    <div class="ml-auto">
        <span>Powered by</span>
        <a href="/#">WebDeveloper</a>
    </div>
</footer>
</body>
<!-- jQuery 3.1.1 -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@coreui/coreui@2.1.16/dist/js/coreui.min.js"></script>
@stack('scripts')

</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.colVis.min.js"></script>
<script src="{{ asset('datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Art-gallery</title>
    <meta content="gallery" name="art-gallery">
    <meta content="gallery" name="gallery">

    <!-- Favicons -->
    <link href="{{asset("assets2/img/favicon.png")}}" rel="icon">
    <link href="{{asset("assets2/img/apple-touch-icon.png")}}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{{asset("assets2/vendor/aos/aos.css")}}" rel="stylesheet">
    <link href="{{asset("assets2/vendor/bootstrap/css/bootstrap.min.css")}}" rel="stylesheet">
    <link href="{{asset("assets2/vendor/bootstrap-icons/bootstrap-icons.css")}}" rel="stylesheet">
    <link href="{{asset("assets2/vendor/boxicons/css/boxicons.min.css")}}" rel="stylesheet">
    <link href="{{asset("assets2/vendor/glightbox/css/glightbox.min.css")}}" rel="stylesheet">
    <link href="{{asset("assets2/vendor/remixicon/remixicon.css")}}" rel="stylesheet">
    <link href="{{asset("assets2/vendor/swiper/swiper-bundle.min.css")}}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{{asset("assets2/css/style.css")}}" rel="stylesheet">


</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="fixed-top ">
    <div class="container d-flex align-items-center justify-content-lg-between">

        <h1 class="logo me-auto me-lg-0"><a href="index.html">A-G<span>.</span></a></h1>

        <nav id="navbar" class="navbar order-last order-lg-0">
            <ul>
                <li><a class="nav-link scrollto active" href="{{url('index')}}">{{__('words.Home page')}}</a></li>
                <li><a class="nav-link scrollto" href="#about">{{__('words.Contact us')}}</a></li>
                <li><a class="nav-link scrollto" href="#services">{{__('words.Servis')}}</a></li>
                <li><a class="nav-link scrollto " href="#portfolio">{{__('words.Portfole')}}</a></li>
                <li><a class="nav-link scrollto" href="#team">{{__('words.Team')}}</a></li>
                <li><a class="nav-link scrollto" href="{{url('gallery')}}">{{__('words.Gallery')}}</a></li>
                <li><a class="nav-link scrollto" href="{{url('contact')}}">{{__('words.Contact')}}</a></li>
                <li class="dropdown"><a href=""><span>{{__('words.Language')}}</span> <i class="bi bi-chevron-down"></i></a>
                <ul>
                  <li><a href="{{url('/lang/en')}}">EN</a></li>
                  <li><a href="{{url('/lang/uz')}}">UZ</a></li>
                  <li><a href="{{url('/lang/ru')}}">RU</a></li>
              </li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

        <a href="{{url('login')}}" class="get-started-btn scrollto">{{__('words.Login')}}</a>

    </div>
</header><!-- End Header -->

<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center justify-content-center">
    <div class="container" data-aos="fade-up">

        <div class="row justify-content-center" data-aos="fade-up" data-aos-delay="150">
            <div class="col-xl-6 col-lg-8">
                <h1>{{__('words.head')}} <span>.</span></h1>
                <h2>{{__('words.head1')}}</h2>
            </div>
        </div>

        <div class="row gy-4 mt-5 justify-content-center" data-aos="zoom-in" data-aos-delay="250">
            <div class="col-xl-2 col-md-4">
                <div class="icon-box">
                    <i class="ri-team-line"></i>
                    <h3><a href="">{{__('words.h1')}}</a></h3>
                </div>
            </div>
            <div class="col-xl-2 col-md-4">
                <div class="icon-box">
                    <i class="ri-gallery-line"></i>
                    <h3><a href="">{{__('words.h2')}}</a></h3>
                </div>
            </div>
            <div class="col-xl-2 col-md-4">
                <div class="icon-box">
                    <i class="ri-video-line"></i>
                    <h3><a href="">{{__('words.h3')}}</a></h3>
                </div>
            </div>
            <div class="col-xl-2 col-md-4">
                <div class="icon-box">
                    <i class="ri-music-2-line"></i>
                    <h3><a href="">{{__('words.h4')}}</a></h3>
                </div>
            </div>
            <div class="col-xl-2 col-md-4">
                <div class="icon-box">
                    <i class="ri-file-line"></i>
                    <h3><a href="">{{__('words.h5')}}</a></h3>
                </div>
            </div>
        </div>

    </div>
</section><!-- End Hero -->

@yield('content')

<!-- ======= Footer ======= -->
<footer id="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row">

                <div class="col-lg-3 col-md-6">
                    <div class="footer-info">
                        <h3>A-G<span>.</span></h3>
                        <p>{!! __('words.f') !!}
                            <br><br>
                             {!! __('words.f2') !!}
                        </p>
                        <div class="social-links mt-3">
                            <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                            <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                            <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                            <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                            <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                        </div>
                    </div>
                </div>

                <div class="col-lg-2 col-md-6 footer-links">
                    <h4>{{__('words.f3')}}</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">{{__('words.Home page')}}</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">{{__('words.Contact us')}}</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">{{__('words.Servis')}}</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">{{__('words.Gallery')}}</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">{{__('words.Portfole')}}</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>{{__('words.f4')}}</h4>
                    <ul>
                       {!! __('words.f5') !!}
                    </ul>
                </div>

                <div class="col-lg-4 col-md-6 footer-newsletter">
                    {!! __('words.f6') !!}

                </div>

            </div>
        </div>
    </div>

    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>Gp</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/gp-free-multipurpose-html-bootstrap-template/ -->
            Designed by <a href="https://bootstrapmade.com/">WebDeveloper</a>
        </div>
    </div>
</footer><!-- End Footer -->

<div id="preloader"></div>
<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>



@yield('script')

<!-- Vendor JS Files -->
<script src="{{asset("assets2/vendor/aos/aos.js")}}"></script>
<script src="{{asset("assets2/vendor/bootstrap/js/bootstrap.bundle.min.js")}}"></script>
<script src="{{asset("assets2/vendor/glightbox/js/glightbox.min.js")}}"></script>
<script src="{{asset("assets2/vendor/isotope-layout/isotope.pkgd.min.js")}}"></script>
<script src="{{asset("assets2/vendor/php-email-form/validate.js")}}"></script>
<script src="{{asset("assets2/vendor/purecounter/purecounter.js")}}"></script>
<script src="{{asset("assets2/vendor/swiper/swiper-bundle.min.js")}}"></script>

<!-- Template Main JS File -->
<script src="{{asset("assets2/js/main.js")}}"></script>

</body>

</html>

resources/views/layouts/menu.blade.php
<li class="nav-item {{ Request::is('users*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('users.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Foydalanuvchilar</span>
    </a>
</li>
<li class="nav-item {{ Request::is('teams*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('teams.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Jamoalar</span>
    </a>
</li>
<li class="nav-item {{ Request::is('teamMembers*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('teamMembers.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Jamoa Azolari</span>
    </a>
</li>


<li class="nav-item {{ Request::is('authors*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('authors.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Avtor</span>
    </a>
</li>
<li class="nav-item {{ Request::is('categories*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('categories.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Toifa</span>
    </a>
</li>
<li class="nav-item {{ Request::is('art*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('art.index') }}">
        <i class="nav-icon icon-cursor"></i>
        <span>Sa'nat</span>
    </a>
</li>

resources/views/layouts/sidebar.blade.php
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav">
            @include('layouts.menu')
        </ul>
    </nav>
    <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>